export const ALLOWED_TAGS: ReadonlySet<string> = new Set([
  'A_ArrayExpr',
  'A_Const',
  'A_Expr',
  'A_Indices',
  'A_Indirection',
  'A_Star',
  'Alias',
  'BoolExpr',
  'BooleanTest',
  'CaseExpr',
  'CaseWhen',
  'CoalesceExpr',
  'CollateClause',
  'ColumnRef',
  'CommonTableExpr',
  'Float',
  'FuncCall',
  'GroupingSet',
  'Integer',
  'JoinExpr',
  'List',
  'MinMaxExpr',
  'NullTest',
  'ParamRef',
  'RangeFunction',
  'RangeSubselect',
  'RangeVar',
  'ResTarget',
  'RowExpr',
  'SelectStmt',
  'SortBy',
  'String',
  'SubLink',
  'TypeCast',
  'TypeName',
  'WindowDef',
  'WithClause',
]);

export const ALLOWED_FIELDS: Readonly<Record<string, ReadonlySet<string>>> = {
  A_ArrayExpr: new Set(['elements', 'location', 'list_start', 'list_end']),
  A_Const: new Set(['ival', 'sval', 'fval', 'boolval', 'bsval', 'isnull', 'location']),
  A_Expr: new Set(['kind', 'lexpr', 'rexpr', 'name', 'location', 'rexpr_list_start', 'rexpr_list_end']),
  A_Indices: new Set(['is_slice', 'lidx', 'uidx']),
  A_Indirection: new Set(['arg', 'indirection']),
  A_Star: new Set([]),
  Alias: new Set(['aliasname', 'colnames']),
  BoolExpr: new Set(['boolop', 'args', 'location']),
  BooleanTest: new Set(['arg', 'booltesttype', 'location']),
  CaseExpr: new Set(['arg', 'args', 'defresult', 'location']),
  CaseWhen: new Set(['expr', 'result', 'location']),
  CoalesceExpr: new Set(['args', 'location']),
  CollateClause: new Set(['arg', 'collname', 'location']),
  ColumnRef: new Set(['fields', 'location']),
  CommonTableExpr: new Set(['ctename', 'ctequery', 'ctematerialized', 'aliascolnames', 'location']),
  Float: new Set(['fval']),
  FuncCall: new Set([
    'funcname',
    'args',
    'agg_order',
    'agg_filter',
    'agg_within_group',
    'agg_star',
    'agg_distinct',
    'func_variadic',
    'over',
    'funcformat',
    'location',
    'name',
    'orderClause',
    'partitionClause',
    'frameOptions',
    'startOffset',
    'endOffset',
  ]),
  GroupingSet: new Set(['kind', 'content', 'location']),
  Integer: new Set(['ival']),
  JoinExpr: new Set([
    'jointype',
    'isNatural',
    'larg',
    'rarg',
    'usingClause',
    'quals',
    'alias',
    'join_using_alias',
  ]),
  List: new Set(['items']),
  MinMaxExpr: new Set(['op', 'args', 'location']),
  NullTest: new Set(['arg', 'nulltesttype', 'location']),
  ParamRef: new Set(['number', 'location']),
  RangeFunction: new Set([
    'lateral',
    'ordinality',
    'is_rowsfrom',
    'functions',
    'alias',
    'aliasname',
    'coldeflist',
  ]),
  RangeSubselect: new Set(['lateral', 'subquery', 'alias', 'aliasname']),
  RangeVar: new Set([
    'catalogname',
    'schemaname',
    'relname',
    'inh',
    'relpersistence',
    'alias',
    'aliasname',
    'location',
  ]),
  ResTarget: new Set(['name', 'indirection', 'val', 'location']),
  RowExpr: new Set(['args', 'row_format', 'colnames', 'location']),
  SelectStmt: new Set([
    'distinctClause',
    'targetList',
    'fromClause',
    'whereClause',
    'groupClause',
    'groupDistinct',
    'havingClause',
    'windowClause',
    'valuesLists',
    'sortClause',
    'limitOffset',
    'limitCount',
    'limitOption',
    'withClause',
    'op',
    'all',
    'larg',
    'rarg',
    'ctes',
  ]),
  SortBy: new Set(['node', 'sortby_dir', 'sortby_nulls', 'useOp', 'location']),
  String: new Set(['sval']),
  SubLink: new Set(['subLinkType', 'subLinkId', 'testexpr', 'operName', 'subselect', 'location']),
  TypeCast: new Set([
    'arg',
    'typeName',
    'location',
    'names',
    'typemod',
    'setof',
    'pct_type',
    'typmods',
    'arrayBounds',
  ]),
  TypeName: new Set([
    'names',
    'typeOid',
    'setof',
    'pct_type',
    'typmods',
    'typemod',
    'arrayBounds',
    'location',
  ]),
  WindowDef: new Set([
    'name',
    'refname',
    'partitionClause',
    'orderClause',
    'frameOptions',
    'startOffset',
    'endOffset',
    'location',
  ]),
  WithClause: new Set(['ctes', 'recursive', 'location']),
};
